name: Android Build

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 🧹 Удаление кэша Gradle вручную (если был повреждён)
      - name: Remove Gradle caches manually
        run: rm -rf $HOME/.gradle/caches

      - name: Clean build directory
        run: ./gradlew clean

      - name: Print app dependencies
        run: ./gradlew :app:dependencies --configuration debugCompileClasspath

      - name: Build with Gradle
        run: ./gradlew assembleDebug
